//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package SiiEnvio.generatedClasses.cl.sii.siiDte;

import java.math.BigInteger;
import javax.xml.datatype.XMLGregorianCalendar;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.xml.bind.annotation.XmlValue;


/**
 * Codigo Autorizacion Folios
 * 
 * <p>Java class for CAFType complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType name="CAFType">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="DA">
 *           <complexType>
 *             <complexContent>
 *               <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 <sequence>
 *                   <element name="RE" type="{http://www.sii.cl/SiiDte}RUTType"/>
 *                   <element name="RS">
 *                     <simpleType>
 *                       <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         <minLength value="1"/>
 *                         <maxLength value="40"/>
 *                       </restriction>
 *                     </simpleType>
 *                   </element>
 *                   <element name="TD" type="{http://www.sii.cl/SiiDte}DTEType"/>
 *                   <element name="RNG">
 *                     <complexType>
 *                       <complexContent>
 *                         <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           <sequence>
 *                             <element name="D" type="{http://www.sii.cl/SiiDte}FolioType"/>
 *                             <element name="H" type="{http://www.sii.cl/SiiDte}FolioType"/>
 *                           </sequence>
 *                         </restriction>
 *                       </complexContent>
 *                     </complexType>
 *                   </element>
 *                   <element name="FA" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *                   <choice>
 *                     <element name="RSAPK">
 *                       <complexType>
 *                         <complexContent>
 *                           <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                             <sequence>
 *                               <element name="M" type="{http://www.w3.org/2001/XMLSchema}base64Binary"/>
 *                               <element name="E" type="{http://www.w3.org/2001/XMLSchema}base64Binary"/>
 *                             </sequence>
 *                           </restriction>
 *                         </complexContent>
 *                       </complexType>
 *                     </element>
 *                     <element name="DSAPK">
 *                       <complexType>
 *                         <complexContent>
 *                           <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                             <sequence>
 *                               <element name="P" type="{http://www.w3.org/2001/XMLSchema}base64Binary"/>
 *                               <element name="Q" type="{http://www.w3.org/2001/XMLSchema}base64Binary"/>
 *                               <element name="G" type="{http://www.w3.org/2001/XMLSchema}base64Binary"/>
 *                               <element name="Y" type="{http://www.w3.org/2001/XMLSchema}base64Binary"/>
 *                             </sequence>
 *                           </restriction>
 *                         </complexContent>
 *                       </complexType>
 *                     </element>
 *                   </choice>
 *                   <element name="IDK" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *                 </sequence>
 *               </restriction>
 *             </complexContent>
 *           </complexType>
 *         </element>
 *         <element name="FRMA">
 *           <complexType>
 *             <simpleContent>
 *               <extension base="<http://www.w3.org/2001/XMLSchema>base64Binary">
 *                 <attribute name="algoritmo" use="required" type="{http://www.w3.org/2001/XMLSchema}string" fixed="SHA1withRSA" />
 *               </extension>
 *             </simpleContent>
 *           </complexType>
 *         </element>
 *       </sequence>
 *       <attribute name="version" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" fixed="1.0" />
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CAFType", propOrder = {
    "da",
    "frma"
})
public class CAFType {

    /**
     * Datos de Autorizacion de Folios
     * 
     */
    @XmlElement(name = "DA", required = true)
    protected CAFType.DA da;
    /**
     * Firma Digital (RSA) del SII Sobre DA
     * 
     */
    @XmlElement(name = "FRMA", required = true)
    protected CAFType.FRMA frma;
    @XmlAttribute(name = "version", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String version;

    /**
     * Datos de Autorizacion de Folios
     * 
     * @return
     *     possible object is
     *     {@link CAFType.DA }
     *     
     */
    public CAFType.DA getDA() {
        return da;
    }

    /**
     * Sets the value of the da property.
     * 
     * @param value
     *     allowed object is
     *     {@link CAFType.DA }
     *     
     * @see #getDA()
     */
    public void setDA(CAFType.DA value) {
        this.da = value;
    }

    /**
     * Firma Digital (RSA) del SII Sobre DA
     * 
     * @return
     *     possible object is
     *     {@link CAFType.FRMA }
     *     
     */
    public CAFType.FRMA getFRMA() {
        return frma;
    }

    /**
     * Sets the value of the frma property.
     * 
     * @param value
     *     allowed object is
     *     {@link CAFType.FRMA }
     *     
     * @see #getFRMA()
     */
    public void setFRMA(CAFType.FRMA value) {
        this.frma = value;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVersion() {
        if (version == null) {
            return "1.0";
        } else {
            return version;
        }
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVersion(String value) {
        this.version = value;
    }


    /**
     * <p>Java class for anonymous complex type</p>.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.</p>
     * 
     * <pre>{@code
     * <complexType>
     *   <complexContent>
     *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       <sequence>
     *         <element name="RE" type="{http://www.sii.cl/SiiDte}RUTType"/>
     *         <element name="RS">
     *           <simpleType>
     *             <restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               <minLength value="1"/>
     *               <maxLength value="40"/>
     *             </restriction>
     *           </simpleType>
     *         </element>
     *         <element name="TD" type="{http://www.sii.cl/SiiDte}DTEType"/>
     *         <element name="RNG">
     *           <complexType>
     *             <complexContent>
     *               <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 <sequence>
     *                   <element name="D" type="{http://www.sii.cl/SiiDte}FolioType"/>
     *                   <element name="H" type="{http://www.sii.cl/SiiDte}FolioType"/>
     *                 </sequence>
     *               </restriction>
     *             </complexContent>
     *           </complexType>
     *         </element>
     *         <element name="FA" type="{http://www.w3.org/2001/XMLSchema}date"/>
     *         <choice>
     *           <element name="RSAPK">
     *             <complexType>
     *               <complexContent>
     *                 <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                   <sequence>
     *                     <element name="M" type="{http://www.w3.org/2001/XMLSchema}base64Binary"/>
     *                     <element name="E" type="{http://www.w3.org/2001/XMLSchema}base64Binary"/>
     *                   </sequence>
     *                 </restriction>
     *               </complexContent>
     *             </complexType>
     *           </element>
     *           <element name="DSAPK">
     *             <complexType>
     *               <complexContent>
     *                 <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                   <sequence>
     *                     <element name="P" type="{http://www.w3.org/2001/XMLSchema}base64Binary"/>
     *                     <element name="Q" type="{http://www.w3.org/2001/XMLSchema}base64Binary"/>
     *                     <element name="G" type="{http://www.w3.org/2001/XMLSchema}base64Binary"/>
     *                     <element name="Y" type="{http://www.w3.org/2001/XMLSchema}base64Binary"/>
     *                   </sequence>
     *                 </restriction>
     *               </complexContent>
     *             </complexType>
     *           </element>
     *         </choice>
     *         <element name="IDK" type="{http://www.w3.org/2001/XMLSchema}long"/>
     *       </sequence>
     *     </restriction>
     *   </complexContent>
     * </complexType>
     * }</pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "re",
        "rs",
        "td",
        "rng",
        "fa",
        "rsapk",
        "dsapk",
        "idk"
    })
    public static class DA {

        /**
         * RUT Emisor
         * 
         */
        @XmlElement(name = "RE", required = true)
        protected String re;
        /**
         * Razon Social Emisor
         * 
         */
        @XmlElement(name = "RS", required = true)
        protected String rs;
        /**
         * Tipo DTE
         * 
         */
        @XmlElement(name = "TD", required = true)
        @XmlSchemaType(name = "positiveInteger")
        protected BigInteger td;
        /**
         * Rango Autorizado de Folios
         * 
         */
        @XmlElement(name = "RNG", required = true)
        protected CAFType.DA.RNG rng;
        /**
         * Fecha Autorizacion en Formato
         * 									AAAA-MM-DD
         * 
         */
        @XmlElement(name = "FA", required = true)
        @XmlSchemaType(name = "date")
        protected XMLGregorianCalendar fa;
        /**
         * Clave Publica RSA del
         * 										Solicitante
         * 
         */
        @XmlElement(name = "RSAPK")
        protected CAFType.DA.RSAPK rsapk;
        /**
         * Clave Publica DSA del
         * 										Solicitante
         * 
         */
        @XmlElement(name = "DSAPK")
        protected CAFType.DA.DSAPK dsapk;
        /**
         * Identificador de Llave
         * 
         */
        @XmlElement(name = "IDK")
        protected long idk;

        /**
         * RUT Emisor
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRE() {
            return re;
        }

        /**
         * Sets the value of the re property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         * @see #getRE()
         */
        public void setRE(String value) {
            this.re = value;
        }

        /**
         * Razon Social Emisor
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRS() {
            return rs;
        }

        /**
         * Sets the value of the rs property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         * @see #getRS()
         */
        public void setRS(String value) {
            this.rs = value;
        }

        /**
         * Tipo DTE
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getTD() {
            return td;
        }

        /**
         * Sets the value of the td property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         * @see #getTD()
         */
        public void setTD(BigInteger value) {
            this.td = value;
        }

        /**
         * Rango Autorizado de Folios
         * 
         * @return
         *     possible object is
         *     {@link CAFType.DA.RNG }
         *     
         */
        public CAFType.DA.RNG getRNG() {
            return rng;
        }

        /**
         * Sets the value of the rng property.
         * 
         * @param value
         *     allowed object is
         *     {@link CAFType.DA.RNG }
         *     
         * @see #getRNG()
         */
        public void setRNG(CAFType.DA.RNG value) {
            this.rng = value;
        }

        /**
         * Fecha Autorizacion en Formato
         * 									AAAA-MM-DD
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getFA() {
            return fa;
        }

        /**
         * Sets the value of the fa property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         * @see #getFA()
         */
        public void setFA(XMLGregorianCalendar value) {
            this.fa = value;
        }

        /**
         * Clave Publica RSA del
         * 										Solicitante
         * 
         * @return
         *     possible object is
         *     {@link CAFType.DA.RSAPK }
         *     
         */
        public CAFType.DA.RSAPK getRSAPK() {
            return rsapk;
        }

        /**
         * Sets the value of the rsapk property.
         * 
         * @param value
         *     allowed object is
         *     {@link CAFType.DA.RSAPK }
         *     
         * @see #getRSAPK()
         */
        public void setRSAPK(CAFType.DA.RSAPK value) {
            this.rsapk = value;
        }

        /**
         * Clave Publica DSA del
         * 										Solicitante
         * 
         * @return
         *     possible object is
         *     {@link CAFType.DA.DSAPK }
         *     
         */
        public CAFType.DA.DSAPK getDSAPK() {
            return dsapk;
        }

        /**
         * Sets the value of the dsapk property.
         * 
         * @param value
         *     allowed object is
         *     {@link CAFType.DA.DSAPK }
         *     
         * @see #getDSAPK()
         */
        public void setDSAPK(CAFType.DA.DSAPK value) {
            this.dsapk = value;
        }

        /**
         * Identificador de Llave
         * 
         */
        public long getIDK() {
            return idk;
        }

        /**
         * Sets the value of the idk property.
         * 
         */
        public void setIDK(long value) {
            this.idk = value;
        }


        /**
         * <p>Java class for anonymous complex type</p>.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.</p>
         * 
         * <pre>{@code
         * <complexType>
         *   <complexContent>
         *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       <sequence>
         *         <element name="P" type="{http://www.w3.org/2001/XMLSchema}base64Binary"/>
         *         <element name="Q" type="{http://www.w3.org/2001/XMLSchema}base64Binary"/>
         *         <element name="G" type="{http://www.w3.org/2001/XMLSchema}base64Binary"/>
         *         <element name="Y" type="{http://www.w3.org/2001/XMLSchema}base64Binary"/>
         *       </sequence>
         *     </restriction>
         *   </complexContent>
         * </complexType>
         * }</pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "p",
            "q",
            "g",
            "y"
        })
        public static class DSAPK {

            /**
             * Modulo Primo
             * 
             */
            @XmlElement(name = "P", required = true)
            protected byte[] p;
            /**
             * Entero Divisor de P
             * 													- 1
             * 
             */
            @XmlElement(name = "Q", required = true)
            protected byte[] q;
            /**
             * Entero f(P, Q)
             * 
             */
            @XmlElement(name = "G", required = true)
            protected byte[] g;
            /**
             * G**X mod P
             * 
             */
            @XmlElement(name = "Y", required = true)
            protected byte[] y;

            /**
             * Modulo Primo
             * 
             * @return
             *     possible object is
             *     byte[]
             */
            public byte[] getP() {
                return p;
            }

            /**
             * Sets the value of the p property.
             * 
             * @param value
             *     allowed object is
             *     byte[]
             * @see #getP()
             */
            public void setP(byte[] value) {
                this.p = value;
            }

            /**
             * Entero Divisor de P
             * 													- 1
             * 
             * @return
             *     possible object is
             *     byte[]
             */
            public byte[] getQ() {
                return q;
            }

            /**
             * Sets the value of the q property.
             * 
             * @param value
             *     allowed object is
             *     byte[]
             * @see #getQ()
             */
            public void setQ(byte[] value) {
                this.q = value;
            }

            /**
             * Entero f(P, Q)
             * 
             * @return
             *     possible object is
             *     byte[]
             */
            public byte[] getG() {
                return g;
            }

            /**
             * Sets the value of the g property.
             * 
             * @param value
             *     allowed object is
             *     byte[]
             * @see #getG()
             */
            public void setG(byte[] value) {
                this.g = value;
            }

            /**
             * G**X mod P
             * 
             * @return
             *     possible object is
             *     byte[]
             */
            public byte[] getY() {
                return y;
            }

            /**
             * Sets the value of the y property.
             * 
             * @param value
             *     allowed object is
             *     byte[]
             * @see #getY()
             */
            public void setY(byte[] value) {
                this.y = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type</p>.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.</p>
         * 
         * <pre>{@code
         * <complexType>
         *   <complexContent>
         *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       <sequence>
         *         <element name="D" type="{http://www.sii.cl/SiiDte}FolioType"/>
         *         <element name="H" type="{http://www.sii.cl/SiiDte}FolioType"/>
         *       </sequence>
         *     </restriction>
         *   </complexContent>
         * </complexType>
         * }</pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "d",
            "h"
        })
        public static class RNG {

            /**
             * Folio Inicial (Desde)
             * 
             */
            @XmlElement(name = "D", required = true)
            @XmlSchemaType(name = "positiveInteger")
            protected BigInteger d;
            /**
             * Folio Final (Hasta)
             * 
             */
            @XmlElement(name = "H", required = true)
            @XmlSchemaType(name = "positiveInteger")
            protected BigInteger h;

            /**
             * Folio Inicial (Desde)
             * 
             * @return
             *     possible object is
             *     {@link BigInteger }
             *     
             */
            public BigInteger getD() {
                return d;
            }

            /**
             * Sets the value of the d property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigInteger }
             *     
             * @see #getD()
             */
            public void setD(BigInteger value) {
                this.d = value;
            }

            /**
             * Folio Final (Hasta)
             * 
             * @return
             *     possible object is
             *     {@link BigInteger }
             *     
             */
            public BigInteger getH() {
                return h;
            }

            /**
             * Sets the value of the h property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigInteger }
             *     
             * @see #getH()
             */
            public void setH(BigInteger value) {
                this.h = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type</p>.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.</p>
         * 
         * <pre>{@code
         * <complexType>
         *   <complexContent>
         *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       <sequence>
         *         <element name="M" type="{http://www.w3.org/2001/XMLSchema}base64Binary"/>
         *         <element name="E" type="{http://www.w3.org/2001/XMLSchema}base64Binary"/>
         *       </sequence>
         *     </restriction>
         *   </complexContent>
         * </complexType>
         * }</pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "m",
            "e"
        })
        public static class RSAPK {

            /**
             * Modulo RSA
             * 
             */
            @XmlElement(name = "M", required = true)
            protected byte[] m;
            /**
             * Exponente RSA
             * 
             */
            @XmlElement(name = "E", required = true)
            protected byte[] e;

            /**
             * Modulo RSA
             * 
             * @return
             *     possible object is
             *     byte[]
             */
            public byte[] getM() {
                return m;
            }

            /**
             * Sets the value of the m property.
             * 
             * @param value
             *     allowed object is
             *     byte[]
             * @see #getM()
             */
            public void setM(byte[] value) {
                this.m = value;
            }

            /**
             * Exponente RSA
             * 
             * @return
             *     possible object is
             *     byte[]
             */
            public byte[] getE() {
                return e;
            }

            /**
             * Sets the value of the e property.
             * 
             * @param value
             *     allowed object is
             *     byte[]
             * @see #getE()
             */
            public void setE(byte[] value) {
                this.e = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type</p>.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.</p>
     * 
     * <pre>{@code
     * <complexType>
     *   <simpleContent>
     *     <extension base="<http://www.w3.org/2001/XMLSchema>base64Binary">
     *       <attribute name="algoritmo" use="required" type="{http://www.w3.org/2001/XMLSchema}string" fixed="SHA1withRSA" />
     *     </extension>
     *   </simpleContent>
     * </complexType>
     * }</pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class FRMA {

        @XmlValue
        protected byte[] value;
        @XmlAttribute(name = "algoritmo", required = true)
        protected String algoritmo;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     byte[]
         */
        public byte[] getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     byte[]
         */
        public void setValue(byte[] value) {
            this.value = value;
        }

        /**
         * Gets the value of the algoritmo property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAlgoritmo() {
            if (algoritmo == null) {
                return "SHA1withRSA";
            } else {
                return algoritmo;
            }
        }

        /**
         * Sets the value of the algoritmo property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAlgoritmo(String value) {
            this.algoritmo = value;
        }

    }

}
