//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package SiiEnvio.generatedClasses.cl.sii.siiDte;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType>
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="RESP_BODY">
 *           <complexType>
 *             <complexContent>
 *               <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 <choice>
 *                   <element name="TOKEN" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   <element name="SEMILLA" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 </choice>
 *               </restriction>
 *             </complexContent>
 *           </complexType>
 *         </element>
 *         <element name="RESP_HDR">
 *           <complexType>
 *             <complexContent>
 *               <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 <sequence>
 *                   <element name="ESTADO" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   <choice>
 *                     <element name="GLOSA" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                     <sequence>
 *                       <element name="GLOSA_ESTADO" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                       <element name="ERR_CODE" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                       <element name="NUM_ATENCION" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                     </sequence>
 *                   </choice>
 *                 </sequence>
 *               </restriction>
 *             </complexContent>
 *           </complexType>
 *         </element>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "respbody",
    "resphdr"
})
@XmlRootElement(name = "RESPUESTA", namespace = "http://www.sii.cl/XMLSchema")
public class RESPUESTA {

    @XmlElement(name = "RESP_BODY", namespace = "http://www.sii.cl/XMLSchema", required = true)
    protected RESPUESTA.RESPBODY respbody;
    @XmlElement(name = "RESP_HDR", namespace = "http://www.sii.cl/XMLSchema", required = true)
    protected RESPUESTA.RESPHDR resphdr;

    /**
     * Gets the value of the respbody property.
     * 
     * @return
     *     possible object is
     *     {@link RESPUESTA.RESPBODY }
     *     
     */
    public RESPUESTA.RESPBODY getRESPBODY() {
        return respbody;
    }

    /**
     * Sets the value of the respbody property.
     * 
     * @param value
     *     allowed object is
     *     {@link RESPUESTA.RESPBODY }
     *     
     */
    public void setRESPBODY(RESPUESTA.RESPBODY value) {
        this.respbody = value;
    }

    /**
     * Gets the value of the resphdr property.
     * 
     * @return
     *     possible object is
     *     {@link RESPUESTA.RESPHDR }
     *     
     */
    public RESPUESTA.RESPHDR getRESPHDR() {
        return resphdr;
    }

    /**
     * Sets the value of the resphdr property.
     * 
     * @param value
     *     allowed object is
     *     {@link RESPUESTA.RESPHDR }
     *     
     */
    public void setRESPHDR(RESPUESTA.RESPHDR value) {
        this.resphdr = value;
    }


    /**
     * <p>Java class for anonymous complex type</p>.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.</p>
     * 
     * <pre>{@code
     * <complexType>
     *   <complexContent>
     *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       <choice>
     *         <element name="TOKEN" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         <element name="SEMILLA" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       </choice>
     *     </restriction>
     *   </complexContent>
     * </complexType>
     * }</pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "token",
        "semilla"
    })
    public static class RESPBODY {

        @XmlElement(name = "TOKEN", namespace = "http://www.sii.cl/XMLSchema")
        protected String token;
        @XmlElement(name = "SEMILLA", namespace = "http://www.sii.cl/XMLSchema")
        protected String semilla;

        /**
         * Gets the value of the token property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTOKEN() {
            return token;
        }

        /**
         * Sets the value of the token property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTOKEN(String value) {
            this.token = value;
        }

        /**
         * Gets the value of the semilla property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSEMILLA() {
            return semilla;
        }

        /**
         * Sets the value of the semilla property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSEMILLA(String value) {
            this.semilla = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type</p>.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.</p>
     * 
     * <pre>{@code
     * <complexType>
     *   <complexContent>
     *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       <sequence>
     *         <element name="ESTADO" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         <choice>
     *           <element name="GLOSA" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *           <sequence>
     *             <element name="GLOSA_ESTADO" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *             <element name="ERR_CODE" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *             <element name="NUM_ATENCION" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *           </sequence>
     *         </choice>
     *       </sequence>
     *     </restriction>
     *   </complexContent>
     * </complexType>
     * }</pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "estado",
        "glosa",
        "glosaestado",
        "errcode",
        "numatencion"
    })
    public static class RESPHDR {

        @XmlElement(name = "ESTADO", namespace = "http://www.sii.cl/XMLSchema")
        protected int estado;
        @XmlElement(name = "GLOSA", namespace = "http://www.sii.cl/XMLSchema")
        protected String glosa;
        @XmlElement(name = "GLOSA_ESTADO", namespace = "http://www.sii.cl/XMLSchema")
        protected String glosaestado;
        @XmlElement(name = "ERR_CODE", namespace = "http://www.sii.cl/XMLSchema")
        protected Integer errcode;
        @XmlElement(name = "NUM_ATENCION", namespace = "http://www.sii.cl/XMLSchema")
        protected String numatencion;

        /**
         * Gets the value of the estado property.
         * 
         */
        public int getESTADO() {
            return estado;
        }

        /**
         * Sets the value of the estado property.
         * 
         */
        public void setESTADO(int value) {
            this.estado = value;
        }

        /**
         * Gets the value of the glosa property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getGLOSA() {
            return glosa;
        }

        /**
         * Sets the value of the glosa property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setGLOSA(String value) {
            this.glosa = value;
        }

        /**
         * Gets the value of the glosaestado property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getGLOSAESTADO() {
            return glosaestado;
        }

        /**
         * Sets the value of the glosaestado property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setGLOSAESTADO(String value) {
            this.glosaestado = value;
        }

        /**
         * Gets the value of the errcode property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getERRCODE() {
            return errcode;
        }

        /**
         * Sets the value of the errcode property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setERRCODE(Integer value) {
            this.errcode = value;
        }

        /**
         * Gets the value of the numatencion property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getNUMATENCION() {
            return numatencion;
        }

        /**
         * Sets the value of the numatencion property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setNUMATENCION(String value) {
            this.numatencion = value;
        }

    }

}
